export * from './Icon1624'
export * from './Icon162ArrovsV1'
export * from './Icon162ArrovsV2'
export * from './Icon162ArrovsV3'
export * from './Icon162ArrovsV4'
export * from './Icon162ArrovsV5'
export * from './Icon162Bubbles'
export * from './Icon162Pages'
export * from './Icon162Users'
export * from './Icon164Arrows'
export * from './Icon164ArrowsV2'
export * from './Icon16Add'
export * from './Icon16AddV1'
export * from './Icon16AddFolder'
export * from './Icon16AddNew'
export * from './Icon16AddPage'
export * from './Icon16AddUser'
export * from './Icon16AlarmClock'
export * from './Icon16Alert'
export * from './Icon16ArrowDownV1'
export * from './Icon16ArrowDownV2'
export * from './Icon16ArrowDownV3'
export * from './Icon16ArrowDownV4'
export * from './Icon16ArrowDownV5'
export * from './Icon16ArrowDownInCircle'
export * from './Icon16ArrowLeftV1'
export * from './Icon16ArrowLeftV2'
export * from './Icon16ArrowLeftV3'
export * from './Icon16ArrowRightV1'
export * from './Icon16ArrowRightV2'
export * from './Icon16ArrowRightV3'
export * from './Icon16ArrowRightInCircle'
export * from './Icon16ArrowUpV1'
export * from './Icon16ArrowUpV2'
export * from './Icon16ArrowUpV3'
export * from './Icon16ArrowUpV4'
export * from './Icon16ArrowUpInCircle'
export * from './Icon16Avatar'
export * from './Icon16AvatarInBubble'
export * from './Icon16Basket'
export * from './Icon16BellV1'
export * from './Icon16BellV2'
export * from './Icon16BillV1'
export * from './Icon16BillV2'
export * from './Icon16Bubble'
export * from './Icon16BubbleEllipsis'
export * from './Icon16BubbleExclaim'
export * from './Icon16BubblePluse'
export * from './Icon16BubbleSmile'
export * from './Icon16Burger'
export * from './Icon16Calendar'
export * from './Icon16CalendarCheck'
export * from './Icon16CalendarCross'
export * from './Icon16CalendarMinus'
export * from './Icon16CalendarPluse'
export * from './Icon16CardV1'
export * from './Icon16CardV2'
export * from './Icon16Case'
export * from './Icon16Cash'
export * from './Icon16CashRubles'
export * from './Icon16Check'
export * from './Icon16CheckInCircle'
export * from './Icon16CheckPage'
export * from './Icon16CircleArrowV1'
export * from './Icon16CircleArrowV2'
export * from './Icon16CircleArrowV3'
export * from './Icon16CircleInASquare'
export * from './Icon16Cloud'
export * from './Icon16CloudCheck'
export * from './Icon16CloudCross'
export * from './Icon16CloudDown'
export * from './Icon16CloudUp'
export * from './Icon16CopyV1'
export * from './Icon16CopyV2'
export * from './Icon16CopyV3'
export * from './Icon16Cross'
export * from './Icon16CrossInCircle'
export * from './Icon16CrossInCircleV2'
export * from './Icon16DiagramV1'
export * from './Icon16DiagramV2'
export * from './Icon16Download'
export * from './Icon16DownloadV3'
export * from './Icon16DownloadV4'
export * from './Icon16Edit'
export * from './Icon16EyeClosed'
export * from './Icon16EyeOpen'
export * from './Icon16FlagV1'
export * from './Icon16FlagV2'
export * from './Icon16Folder'
export * from './Icon16GraphV1'
export * from './Icon16GraphV2'
export * from './Icon16GraphV3'
export * from './Icon16GraphV4'
export * from './Icon16GraphV5'
export * from './Icon16GraphV6'
export * from './Icon16GraphV7'
export * from './Icon16GraphV8'
export * from './Icon16HomeV1'
export * from './Icon16HomeV2'
export * from './Icon16InfoInCircle'
export * from './Icon16LinkV1'
export * from './Icon16LinkV2'
export * from './Icon16ListArrowV1'
export * from './Icon16ListArrowV2'
export * from './Icon16ListArrowV3'
export * from './Icon16ListArrowV4'
export * from './Icon16Loader'
export * from './Icon16Lock'
export * from './Icon16Login'
export * from './Icon16Logout'
export * from './Icon16Mail'
export * from './Icon16MailCheck'
export * from './Icon16MailCome'
export * from './Icon16MailCross'
export * from './Icon16MailLock'
export * from './Icon16MailOpen'
export * from './Icon16MailOutcome'
export * from './Icon16Map'
export * from './Icon16MarkerV1'
export * from './Icon16MarkerV2'
export * from './Icon16MarkerV3'
export * from './Icon16MarkerPluse'
export * from './Icon16MinusInCircle'
export * from './Icon16Page'
export * from './Icon16PageList'
export * from './Icon16PaperclipV1'
export * from './Icon16PaperclipV2'
export * from './Icon16PlusOrMinus'
export * from './Icon16Pluse'
export * from './Icon16Present'
export * from './Icon16QuestionInCircle'
export * from './Icon16Refund'
export * from './Icon16RublesV1'
export * from './Icon16RublesV2'
export * from './Icon16Safe'
export * from './Icon16Sale'
export * from './Icon16SaleV3'
export * from './Icon16SaleBill'
export * from './Icon16SandScalesV1'
export * from './Icon16SandScalesV2'
export * from './Icon16SandScalesV3'
export * from './Icon16Search'
export * from './Icon16SettingsV1'
export * from './Icon16SettingsV2'
export * from './Icon16Shild'
export * from './Icon16ShildCheck'
export * from './Icon16ShildCross'
export * from './Icon16Snap'
export * from './Icon16Star'
export * from './Icon16Switch'
export * from './Icon16Target'
export * from './Icon16TimeV1'
export * from './Icon16TimeV2'
export * from './Icon16TimeV3'
export * from './Icon16TimeV4'
export * from './Icon16TimeV5'
export * from './Icon16Timer'
export * from './Icon16Trash'
export * from './Icon16Unlink'
export * from './Icon16Unlock'
export * from './Icon16Untarget'
export * from './Icon16UploadV2'
export * from './Icon16UploadV3'
export * from './Icon16User'
export * from './Icon16Wallet'
export * from './Icon16WalletAdd'
export * from './Icon16WalletIn'
export * from './Icon16WalletOut'
export * from './Icon16WayV1'
export * from './Icon16WayV2'
export * from './Icon16Zoom'
export * from './Icon16ZoomMinuse'
export * from './Icon2424'
export * from './Icon242ArrovsV1'
export * from './Icon242ArrovsV2'
export * from './Icon242ArrovsV3'
export * from './Icon242ArrovsV4'
export * from './Icon242ArrovsV5'
export * from './Icon242Bubbles'
export * from './Icon242Pages'
export * from './Icon242Users'
export * from './Icon244Arrows'
export * from './Icon244ArrowsV2'
export * from './Icon24Add'
export * from './Icon24AddV1'
export * from './Icon24AddFolder'
export * from './Icon24AddNew'
export * from './Icon24AddPage'
export * from './Icon24AddUser'
export * from './Icon24AlarmClock'
export * from './Icon24Alert'
export * from './Icon24ArrowDownV1'
export * from './Icon24ArrowDownV2'
export * from './Icon24ArrowDownV3'
export * from './Icon24ArrowDownV4'
export * from './Icon24ArrowDownV5'
export * from './Icon24ArrowDownInCircle'
export * from './Icon24ArrowLeftV1'
export * from './Icon24ArrowLeftV2'
export * from './Icon24ArrowLeftV3'
export * from './Icon24ArrowRightV1'
export * from './Icon24ArrowRightV2'
export * from './Icon24ArrowRightV3'
export * from './Icon24ArrowRightInCircle'
export * from './Icon24ArrowUpV1'
export * from './Icon24ArrowUpV2'
export * from './Icon24ArrowUpV3'
export * from './Icon24ArrowUpV4'
export * from './Icon24ArrowUpInCircle'
export * from './Icon24Avatar'
export * from './Icon24AvatarInBubble'
export * from './Icon24Basket'
export * from './Icon24BellV1'
export * from './Icon24BellV2'
export * from './Icon24BillV1'
export * from './Icon24BillV2'
export * from './Icon24Bubble'
export * from './Icon24BubbleEllipsis'
export * from './Icon24BubbleExclaim'
export * from './Icon24BubblePluse'
export * from './Icon24BubbleSmile'
export * from './Icon24Burger'
export * from './Icon24Calendar'
export * from './Icon24CalendarCheck'
export * from './Icon24CalendarCross'
export * from './Icon24CalendarMinus'
export * from './Icon24CalendarPluse'
export * from './Icon24CardV1'
export * from './Icon24CardV2'
export * from './Icon24Case'
export * from './Icon24Cash'
export * from './Icon24CashRubles'
export * from './Icon24Check'
export * from './Icon24CheckInCircle'
export * from './Icon24CheckPage'
export * from './Icon24CircleArrowV1'
export * from './Icon24CircleArrowV2'
export * from './Icon24CircleArrowV3'
export * from './Icon24CircleInASquare'
export * from './Icon24Cloud'
export * from './Icon24CloudCheck'
export * from './Icon24CloudCross'
export * from './Icon24CloudDown'
export * from './Icon24CloudUp'
export * from './Icon24CopyV1'
export * from './Icon24CopyV2'
export * from './Icon24CopyV3'
export * from './Icon24Cross'
export * from './Icon24CrossInCircle'
export * from './Icon24CrossInCircleV2'
export * from './Icon24DiagramV1'
export * from './Icon24DiagramV2'
export * from './Icon24Download'
export * from './Icon24DownloadV3'
export * from './Icon24DownloadV4'
export * from './Icon24Edit'
export * from './Icon24EyeClosed'
export * from './Icon24EyeOpen'
export * from './Icon24FlagV1'
export * from './Icon24FlagV2'
export * from './Icon24Folder'
export * from './Icon24GraphV1'
export * from './Icon24GraphV2'
export * from './Icon24GraphV3'
export * from './Icon24GraphV4'
export * from './Icon24GraphV5'
export * from './Icon24GraphV6'
export * from './Icon24GraphV7'
export * from './Icon24GraphV8'
export * from './Icon24HomeV1'
export * from './Icon24HomeV2'
export * from './Icon24InfoInCircle'
export * from './Icon24LinkV1'
export * from './Icon24LinkV2'
export * from './Icon24ListArrowV1'
export * from './Icon24ListArrowV2'
export * from './Icon24ListArrowV3'
export * from './Icon24ListArrowV4'
export * from './Icon24Loader'
export * from './Icon24Lock'
export * from './Icon24Login'
export * from './Icon24Logout'
export * from './Icon24Mail'
export * from './Icon24MailCheck'
export * from './Icon24MailCome'
export * from './Icon24MailCross'
export * from './Icon24MailLock'
export * from './Icon24MailOpen'
export * from './Icon24MailOutcome'
export * from './Icon24Map'
export * from './Icon24MarkerV1'
export * from './Icon24MarkerV2'
export * from './Icon24MarkerV3'
export * from './Icon24MarkerPluse'
export * from './Icon24MinusInCircle'
export * from './Icon24Page'
export * from './Icon24PageList'
export * from './Icon24PaperclipV1'
export * from './Icon24PaperclipV2'
export * from './Icon24PlusOrMinus'
export * from './Icon24Pluse'
export * from './Icon24Present'
export * from './Icon24QuestionInCircle'
export * from './Icon24Refund'
export * from './Icon24RublesV1'
export * from './Icon24RublesV2'
export * from './Icon24Safe'
export * from './Icon24Sale'
export * from './Icon24SaleV3'
export * from './Icon24SaleBill'
export * from './Icon24SandScalesV1'
export * from './Icon24SandScalesV2'
export * from './Icon24SandScalesV3'
export * from './Icon24Search'
export * from './Icon24SettingsV1'
export * from './Icon24SettingsV2'
export * from './Icon24Shild'
export * from './Icon24ShildCheck'
export * from './Icon24ShildCross'
export * from './Icon24Snap'
export * from './Icon24Star'
export * from './Icon24Switch'
export * from './Icon24Target'
export * from './Icon24TimeV1'
export * from './Icon24TimeV2'
export * from './Icon24TimeV3'
export * from './Icon24TimeV4'
export * from './Icon24TimeV5'
export * from './Icon24Timer'
export * from './Icon24Trash'
export * from './Icon24Unlink'
export * from './Icon24Unlock'
export * from './Icon24Untarget'
export * from './Icon24UploadV2'
export * from './Icon24UploadV3'
export * from './Icon24User'
export * from './Icon24Wallet'
export * from './Icon24WalletAdd'
export * from './Icon24WalletIn'
export * from './Icon24WalletOut'
export * from './Icon24WayV1'
export * from './Icon24WayV2'
export * from './Icon24Zoom'
export * from './Icon24ZoomMinuse'
export * from './Icon3224'
export * from './Icon322ArrovsV1'
export * from './Icon322ArrovsV2'
export * from './Icon322ArrovsV3'
export * from './Icon322ArrovsV4'
export * from './Icon322ArrovsV5'
export * from './Icon322Bubbles'
export * from './Icon322Pages'
export * from './Icon322Users'
export * from './Icon324Arrows'
export * from './Icon324ArrowsV2'
export * from './Icon32Add'
export * from './Icon32AddV1'
export * from './Icon32AddFolder'
export * from './Icon32AddNew'
export * from './Icon32AddPage'
export * from './Icon32AddUser'
export * from './Icon32AlarmClock'
export * from './Icon32Alert'
export * from './Icon32ArrowDownV1'
export * from './Icon32ArrowDownV2'
export * from './Icon32ArrowDownV3'
export * from './Icon32ArrowDownV4'
export * from './Icon32ArrowDownV5'
export * from './Icon32ArrowDownInCircle'
export * from './Icon32ArrowLeftV1'
export * from './Icon32ArrowLeftV2'
export * from './Icon32ArrowLeftV3'
export * from './Icon32ArrowRightV1'
export * from './Icon32ArrowRightV2'
export * from './Icon32ArrowRightV3'
export * from './Icon32ArrowRightInCircle'
export * from './Icon32ArrowUpV1'
export * from './Icon32ArrowUpV2'
export * from './Icon32ArrowUpV3'
export * from './Icon32ArrowUpV4'
export * from './Icon32ArrowUpInCircle'
export * from './Icon32Avatar'
export * from './Icon32AvatarInBubble'
export * from './Icon32Basket'
export * from './Icon32BellV1'
export * from './Icon32BellV2'
export * from './Icon32BillV1'
export * from './Icon32BillV2'
export * from './Icon32Bubble'
export * from './Icon32BubbleEllipsis'
export * from './Icon32BubbleExclaim'
export * from './Icon32BubblePluse'
export * from './Icon32BubbleSmile'
export * from './Icon32Burger'
export * from './Icon32Calendar'
export * from './Icon32CalendarCheck'
export * from './Icon32CalendarCross'
export * from './Icon32CalendarMinus'
export * from './Icon32CalendarPluse'
export * from './Icon32CardV1'
export * from './Icon32CardV2'
export * from './Icon32Case'
export * from './Icon32Cash'
export * from './Icon32CashRubles'
export * from './Icon32Check'
export * from './Icon32CheckInCircle'
export * from './Icon32CheckPage'
export * from './Icon32CircleArrowV1'
export * from './Icon32CircleArrowV2'
export * from './Icon32CircleArrowV3'
export * from './Icon32CircleInASquare'
export * from './Icon32Cloud'
export * from './Icon32CloudCheck'
export * from './Icon32CloudCross'
export * from './Icon32CloudDown'
export * from './Icon32CloudUp'
export * from './Icon32CopyV1'
export * from './Icon32CopyV2'
export * from './Icon32CopyV3'
export * from './Icon32Cross'
export * from './Icon32CrossInCircle'
export * from './Icon32CrossInCircleV2'
export * from './Icon32DiagramV1'
export * from './Icon32DiagramV2'
export * from './Icon32Download'
export * from './Icon32DownloadV3'
export * from './Icon32DownloadV4'
export * from './Icon32Edit'
export * from './Icon32EyeClosed'
export * from './Icon32EyeOpen'
export * from './Icon32FlagV1'
export * from './Icon32FlagV2'
export * from './Icon32Folder'
export * from './Icon32GraphV1'
export * from './Icon32GraphV2'
export * from './Icon32GraphV3'
export * from './Icon32GraphV4'
export * from './Icon32GraphV5'
export * from './Icon32GraphV6'
export * from './Icon32GraphV7'
export * from './Icon32GraphV8'
export * from './Icon32HomeV1'
export * from './Icon32HomeV2'
export * from './Icon32InfoInCircle'
export * from './Icon32LinkV1'
export * from './Icon32LinkV2'
export * from './Icon32ListArrowV1'
export * from './Icon32ListArrowV2'
export * from './Icon32ListArrowV3'
export * from './Icon32ListArrowV4'
export * from './Icon32Loader'
export * from './Icon32Lock'
export * from './Icon32Login'
export * from './Icon32Logout'
export * from './Icon32Mail'
export * from './Icon32MailCheck'
export * from './Icon32MailCome'
export * from './Icon32MailCross'
export * from './Icon32MailLock'
export * from './Icon32MailOpen'
export * from './Icon32MailOutcome'
export * from './Icon32Map'
export * from './Icon32MarkerV1'
export * from './Icon32MarkerV2'
export * from './Icon32MarkerV3'
export * from './Icon32MarkerPluse'
export * from './Icon32MinusInCircle'
export * from './Icon32Page'
export * from './Icon32PageList'
export * from './Icon32PaperclipV2'
export * from './Icon32PaperclipV1'
export * from './Icon32PlusOrMinus'
export * from './Icon32Pluse'
export * from './Icon32Present'
export * from './Icon32QuestionInCircle'
export * from './Icon32Refund'
export * from './Icon32RublesV2'
export * from './Icon32RublesV1'
export * from './Icon32Safe'
export * from './Icon32Sale'
export * from './Icon32SaleV3'
export * from './Icon32SaleBill'
export * from './Icon32SandScalesV1'
export * from './Icon32SandScalesV2'
export * from './Icon32SandScalesV3'
export * from './Icon32Search'
export * from './Icon32SettingsV1'
export * from './Icon32SettingsV2'
export * from './Icon32Shild'
export * from './Icon32ShildCheck'
export * from './Icon32ShildCross'
export * from './Icon32Snap'
export * from './Icon32Star'
export * from './Icon32Switch'
export * from './Icon32Target'
export * from './Icon32TimeV1'
export * from './Icon32TimeV2'
export * from './Icon32TimeV3'
export * from './Icon32TimeV4'
export * from './Icon32TimeV5'
export * from './Icon32Timer'
export * from './Icon32Trash'
export * from './Icon32Unlink'
export * from './Icon32Unlock'
export * from './Icon32Untarget'
export * from './Icon32UploadV2'
export * from './Icon32UploadV3'
export * from './Icon32User'
export * from './Icon32Wallet'
export * from './Icon32WalletAdd'
export * from './Icon32WalletIn'
export * from './Icon32WalletOut'
export * from './Icon32WayV1'
export * from './Icon32WayV2'
export * from './Icon32Zoom'
export * from './Icon32ZoomMinuse'
export * from './Icon4024'
export * from './Icon402ArrovsV1'
export * from './Icon402ArrovsV2'
export * from './Icon402ArrovsV3'
export * from './Icon402ArrovsV4'
export * from './Icon402ArrovsV5'
export * from './Icon402Bubbles'
export * from './Icon402Pages'
export * from './Icon402Users'
export * from './Icon404Arrows'
export * from './Icon404ArrowsV2'
export * from './Icon40Add'
export * from './Icon40AddV1'
export * from './Icon40AddFolder'
export * from './Icon40AddNew'
export * from './Icon40AddPage'
export * from './Icon40AddUser'
export * from './Icon40AlarmClock'
export * from './Icon40Alert'
export * from './Icon40ArrowDownV1'
export * from './Icon40ArrowDownV2'
export * from './Icon40ArrowDownV3'
export * from './Icon40ArrowDownV4'
export * from './Icon40ArrowDownV5'
export * from './Icon40ArrowDownInCircle'
export * from './Icon40ArrowLeftV1'
export * from './Icon40ArrowLeftV2'
export * from './Icon40ArrowLeftV3'
export * from './Icon40ArrowRightV1'
export * from './Icon40ArrowRightV2'
export * from './Icon40ArrowRightV3'
export * from './Icon40ArrowRightInCircle'
export * from './Icon40ArrowUpV1'
export * from './Icon40ArrowUpV2'
export * from './Icon40ArrowUpV3'
export * from './Icon40ArrowUpV4'
export * from './Icon40ArrowUpInCircle'
export * from './Icon40Avatar'
export * from './Icon40AvatarInBubble'
export * from './Icon40Basket'
export * from './Icon40BellV1'
export * from './Icon40BellV2'
export * from './Icon40BillV1'
export * from './Icon40BillV2'
export * from './Icon40Bubble'
export * from './Icon40BubbleEllipsis'
export * from './Icon40BubbleExclaim'
export * from './Icon40BubblePluse'
export * from './Icon40BubbleSmile'
export * from './Icon40Burger'
export * from './Icon40Calendar'
export * from './Icon40CalendarCheck'
export * from './Icon40CalendarCross'
export * from './Icon40CalendarMinus'
export * from './Icon40CalendarPluse'
export * from './Icon40CardV1'
export * from './Icon40CardV2'
export * from './Icon40Case'
export * from './Icon40Cash'
export * from './Icon40CashRubles'
export * from './Icon40Check'
export * from './Icon40CheckInCircle'
export * from './Icon40CheckPage'
export * from './Icon40CircleArrowV1'
export * from './Icon40CircleArrowV2'
export * from './Icon40CircleArrowV3'
export * from './Icon40CircleInASquare'
export * from './Icon40Cloud'
export * from './Icon40CloudCheck'
export * from './Icon40CloudCross'
export * from './Icon40CloudDown'
export * from './Icon40CloudUp'
export * from './Icon40CopyV1'
export * from './Icon40CopyV2'
export * from './Icon40CopyV3'
export * from './Icon40Cross'
export * from './Icon40CrossInCircle'
export * from './Icon40CrossInCircleV2'
export * from './Icon40DiagramV1'
export * from './Icon40DiagramV2'
export * from './Icon40Download'
export * from './Icon40DownloadV3'
export * from './Icon40DownloadV4'
export * from './Icon40Edit'
export * from './Icon40EyeClosed'
export * from './Icon40EyeOpen'
export * from './Icon40FlagV1'
export * from './Icon40FlagV2'
export * from './Icon40Folder'
export * from './Icon40GraphV1'
export * from './Icon40GraphV2'
export * from './Icon40GraphV3'
export * from './Icon40GraphV4'
export * from './Icon40GraphV5'
export * from './Icon40GraphV6'
export * from './Icon40GraphV7'
export * from './Icon40GraphV8'
export * from './Icon40HomeV1'
export * from './Icon40HomeV2'
export * from './Icon40InfoInCircle'
export * from './Icon40LinkV1'
export * from './Icon40LinkV2'
export * from './Icon40ListArrowV1'
export * from './Icon40ListArrowV2'
export * from './Icon40ListArrowV3'
export * from './Icon40ListArrowV4'
export * from './Icon40Loader'
export * from './Icon40Lock'
export * from './Icon40Login'
export * from './Icon40Logout'
export * from './Icon40Mail'
export * from './Icon40MailCheck'
export * from './Icon40MailCome'
export * from './Icon40MailCross'
export * from './Icon40MailLock'
export * from './Icon40MailOpen'
export * from './Icon40MailOutcome'
export * from './Icon40Map'
export * from './Icon40MarkerV1'
export * from './Icon40MarkerV2'
export * from './Icon40MarkerV3'
export * from './Icon40MarkerPluse'
export * from './Icon40MinusInCircle'
export * from './Icon40Page'
export * from './Icon40PageList'
export * from './Icon40PaperclipV1'
export * from './Icon40PaperclipV2'
export * from './Icon40PlusOrMinus'
export * from './Icon40Pluse'
export * from './Icon40Present'
export * from './Icon40QuestionInCircle'
export * from './Icon40Refund'
export * from './Icon40RublesV1'
export * from './Icon40RublesV2'
export * from './Icon40Safe'
export * from './Icon40Sale'
export * from './Icon40SaleV3'
export * from './Icon40SaleBill'
export * from './Icon40SandScalesV1'
export * from './Icon40SandScalesV2'
export * from './Icon40SandScalesV3'
export * from './Icon40Search'
export * from './Icon40SettingsV1'
export * from './Icon40SettingsV2'
export * from './Icon40Shild'
export * from './Icon40ShildCheck'
export * from './Icon40ShildCross'
export * from './Icon40Snap'
export * from './Icon40Star'
export * from './Icon40Switch'
export * from './Icon40Target'
export * from './Icon40TimeV1'
export * from './Icon40TimeV2'
export * from './Icon40TimeV3'
export * from './Icon40TimeV4'
export * from './Icon40TimeV5'
export * from './Icon40Timer'
export * from './Icon40Trash'
export * from './Icon40Unlink'
export * from './Icon40Unlock'
export * from './Icon40Untarget'
export * from './Icon40UploadV2'
export * from './Icon40UploadV3'
export * from './Icon40User'
export * from './Icon40Wallet'
export * from './Icon40WalletAdd'
export * from './Icon40WalletIn'
export * from './Icon40WalletOut'
export * from './Icon40WayV1'
export * from './Icon40WayV2'
export * from './Icon40Zoom'
export * from './Icon40ZoomMinuse'
export type IconSize = 16 | 24 | 32 | 40
export type IconName =
  | '24'
  | '2-arrovs-v1'
  | '2-arrovs-v2'
  | '2-arrovs-v3'
  | '2-arrovs-v4'
  | '2-arrovs-v5'
  | '2-bubbles'
  | '2-pages'
  | '2-users'
  | '4-arrows'
  | '4-arrows-v2'
  | 'add'
  | 'add-v1'
  | 'add-folder'
  | 'add-new'
  | 'add-page'
  | 'add-user'
  | 'alarm-clock'
  | 'alert'
  | 'arrow-down-v1'
  | 'arrow-down-v2'
  | 'arrow-down-v3'
  | 'arrow-down-v4'
  | 'arrow-down-v5'
  | 'arrow-down-in-circle'
  | 'arrow-left-v1'
  | 'arrow-left-v2'
  | 'arrow-left-v3'
  | 'arrow-right-v1'
  | 'arrow-right-v2'
  | 'arrow-right-v3'
  | 'arrow-right-in-circle'
  | 'arrow-up-v1'
  | 'arrow-up-v2'
  | 'arrow-up-v3'
  | 'arrow-up-v4'
  | 'arrow-up-in-circle'
  | 'avatar'
  | 'avatar-in-bubble'
  | 'basket'
  | 'bell-v1'
  | 'bell-v2'
  | 'bill-v1'
  | 'bill-v2'
  | 'bubble'
  | 'bubble-ellipsis'
  | 'bubble-exclaim'
  | 'bubble-pluse'
  | 'bubble-smile'
  | 'burger'
  | 'calendar'
  | 'calendar-check'
  | 'calendar-cross'
  | 'calendar-minus'
  | 'calendar-pluse'
  | 'card-v1'
  | 'card-v2'
  | 'case'
  | 'cash'
  | 'cash-rubles'
  | 'check'
  | 'check-in-circle'
  | 'check-page'
  | 'circle-arrow-v1'
  | 'circle-arrow-v2'
  | 'circle-arrow-v3'
  | 'circle-in-a-square'
  | 'cloud'
  | 'cloud-check'
  | 'cloud-cross'
  | 'cloud-down'
  | 'cloud-up'
  | 'copy-v1'
  | 'copy-v2'
  | 'copy-v3'
  | 'cross'
  | 'cross-in-circle'
  | 'cross-in-circle-v2'
  | 'diagram-v1'
  | 'diagram-v2'
  | 'download'
  | 'download-v3'
  | 'download-v4'
  | 'edit'
  | 'eye-closed'
  | 'eye-open'
  | 'flag-v1'
  | 'flag-v2'
  | 'folder'
  | 'graph-v1'
  | 'graph-v2'
  | 'graph-v3'
  | 'graph-v4'
  | 'graph-v5'
  | 'graph-v6'
  | 'graph-v7'
  | 'graph-v8'
  | 'home-v1'
  | 'home-v2'
  | 'info-in-circle'
  | 'link-v1'
  | 'link-v2'
  | 'list-arrow-v1'
  | 'list-arrow-v2'
  | 'list-arrow-v3'
  | 'list-arrow-v4'
  | 'loader'
  | 'lock'
  | 'login'
  | 'logout'
  | 'mail'
  | 'mail-check'
  | 'mail-come'
  | 'mail-cross'
  | 'mail-lock'
  | 'mail-open'
  | 'mail-outcome'
  | 'map'
  | 'marker-v1'
  | 'marker-v2'
  | 'marker-v3'
  | 'marker-pluse'
  | 'minus-in-circle'
  | 'page'
  | 'page-list'
  | 'paperclip-v1'
  | 'paperclip-v2'
  | 'plus-or-minus'
  | 'pluse'
  | 'present'
  | 'question-in-circle'
  | 'refund'
  | 'rubles-v1'
  | 'rubles-v2'
  | 'safe'
  | 'sale'
  | 'sale-v3'
  | 'sale-bill'
  | 'sand-scales-v1'
  | 'sand-scales-v2'
  | 'sand-scales-v3'
  | 'search'
  | 'settings-v1'
  | 'settings-v2'
  | 'shild'
  | 'shild-check'
  | 'shild-cross'
  | 'snap'
  | 'star'
  | 'switch'
  | 'target'
  | 'time-v1'
  | 'time-v2'
  | 'time-v3'
  | 'time-v4'
  | 'time-v5'
  | 'timer'
  | 'trash'
  | 'unlink'
  | 'unlock'
  | 'untarget'
  | 'upload-v2'
  | 'upload-v3'
  | 'user'
  | 'wallet'
  | 'wallet-add'
  | 'wallet-in'
  | 'wallet-out'
  | 'way-v1'
  | 'way-v2'
  | 'zoom'
  | 'zoom-minuse'
