name: CI
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Build Storybook
        run: yarn sb:build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: 'qiwibot'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'opensource@qiwi.com'
          GIT_COMMITTER_EMAIL: 'opensource@qiwi.com'
          GIT_AUTHOR_NAME: 'QIWI Bot'
          GIT_COMMITTER_NAME: 'QIWI Bot'
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: npm_config_yes=true npx zx-bulk-release --include-private
